@host = localhost
@port = 3000

### Create group
# @name createGroup
POST http://{{host}}:{{port}}/
Content-Type: application/json

{
  "name": "lucas",
  "founder": "5dbe22606de0af00112acb07",
  "pictures": {
    "profile": "base64",
    "banner": "base64"
  },
  "socialNetworks": [
    { "name": "Twitter", "link": "https://twitter.com/_staticvoid" },
    { "name": "GitHub", "link": "https://github.com/khaosdoctor" }
  ],
  "tags": ["javascript","typescript","kubernetes"],
  "organizers": [],
  "location": {
    "city": "São Paulo",
    "state": "São Paulo",
    "country": "Brazil"
  }
}

### List groups
GET http://{{host}}:{{port}}/

### Delete group
# @name deleteGroup
@groupId = 5dbe3480ca33ddc2f7566691

DELETE http://{{host}}:{{port}}/{{groupId}}

### Update group
# @name updateGroup
@groupId = 5dbe3480ca33ddc2f7566691

PUT http://{{host}}:{{port}}/{{groupId}}
Content-Type: application/json

{
  "name": "Lucas Santos",
  "socialNetworks": [
    { "name": "Twitter", "link": "https://twitter.com/_staticvoid" },
    { "name": "GitHub", "link": "https://github.com/khaosdoctor" }
  ],
  "tags": ["javascript","kubernetes"],
  "location": {
    "city": "Santo André"
  }
}

### Get group
# @name getGroup
@groupId = 5dbe3480ca33ddc2f7566691

GET http://{{host}}:{{port}}/{{groupId}}

### Get user groups
# @name getGroup
@userId = 5dbe22606de0af00112acb06

GET http://{{host}}:{{port}}/followers/{{userId}}
